// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmK3-0FS2S0r3MV18QpZIbZt3vxKUA8s0',
    appId: '1:803732607953:web:a2bc00cfd1cf988cbb86f0',
    messagingSenderId: '803732607953',
    projectId: 'flutter-auth-2c34c',
    authDomain: 'flutter-auth-2c34c.firebaseapp.com',
    storageBucket: 'flutter-auth-2c34c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDrIvMB0umv9oEg350kofpmqS4MHldWe0',
    appId: '1:803732607953:android:60a92bdbdc65a817bb86f0',
    messagingSenderId: '803732607953',
    projectId: 'flutter-auth-2c34c',
    storageBucket: 'flutter-auth-2c34c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8F2MtLLyaGkbptFSOiFSnSDMgHEI-iGo',
    appId: '1:803732607953:ios:d3e10556fdcb2276bb86f0',
    messagingSenderId: '803732607953',
    projectId: 'flutter-auth-2c34c',
    storageBucket: 'flutter-auth-2c34c.appspot.com',
    iosBundleId: 'com.example.loginOauth2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8F2MtLLyaGkbptFSOiFSnSDMgHEI-iGo',
    appId: '1:803732607953:ios:d3e10556fdcb2276bb86f0',
    messagingSenderId: '803732607953',
    projectId: 'flutter-auth-2c34c',
    storageBucket: 'flutter-auth-2c34c.appspot.com',
    iosBundleId: 'com.example.loginOauth2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmK3-0FS2S0r3MV18QpZIbZt3vxKUA8s0',
    appId: '1:803732607953:web:d3e603b0a337870fbb86f0',
    messagingSenderId: '803732607953',
    projectId: 'flutter-auth-2c34c',
    authDomain: 'flutter-auth-2c34c.firebaseapp.com',
    storageBucket: 'flutter-auth-2c34c.appspot.com',
  );
}
